repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
        args:
          - --exclude=/(tests)/
          - --line-length=79
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.5
    hooks:
      - id: reorder-python-imports
        args: [--application-directories, ".:src", --py37-plus]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.28.0'  # Update me!
    hooks:
    - id: talisman-commit
      entry: cmd --githook pre-commit
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        exclude: (^test_.*|^tests/test_.*|^tests/.*/test_.*)
        language: python
        language_version: python3
        types: [python]
